/**
 * Stable error-code catalogue — verbatim from Doc 15 §31.
 * These codes are API contract; do not rename. Protected resources may
 * deliberately return RESOURCE_NOT_FOUND instead of AUTHORISATION_DENIED
 * (protected existence, ADR-050).
 */
export const ERROR_CODES = {
  // Authentication / session / context
  AUTHENTICATION_REQUIRED: 401,
  AUTHENTICATION_FAILED: 401,
  STEP_UP_AUTHENTICATION_REQUIRED: 401,
  SESSION_EXPIRED: 401,
  ORGANISATION_CONTEXT_REQUIRED: 400,
  RESEARCH_PROJECT_CONTEXT_REQUIRED: 400,

  // Authorisation / consent / purpose
  AUTHORISATION_DENIED: 403,
  RELATIONSHIP_REQUIRED: 403,
  CONSENT_REQUIRED: 403,
  CONSENT_EXPIRED: 403,
  PURPOSE_NOT_PERMITTED: 403,
  SPECIFIC_PERMISSION_REQUIRED: 403,
  RESOURCE_STATE_BLOCKED: 409,
  VISIBILITY_DENIED: 403,
  BLOCKED_INTERACTION: 403,
  COMMUNICATION_BASIS_REQUIRED: 403,
  COMMUNICATION_BASIS_EXPIRED: 403,
  MUTUAL_ACCEPTANCE_REQUIRED: 403,

  // Matching / connection
  MATCHING_NOT_ACTIVE: 409,
  MATCH_CANDIDATE_EXPIRED: 409,
  MATCH_DECISION_NOT_OWNED: 403,
  MATCH_DECISION_CONFLICT: 409,
  MUTUAL_ACCEPTANCE_NOT_FOUND: 404,
  MUTUAL_ACCEPTANCE_EXPIRED: 409,
  MUTUAL_ACCEPTANCE_INVALIDATED: 409,
  MUTUAL_ACCEPTANCE_ALREADY_CONSUMED: 409,
  CONNECTION_REQUEST_FEATURE_DISABLED: 403,
  CONNECTION_BASIS_INVALID: 409,
  CONNECTION_NOT_ACTIVE: 409,

  // Messaging
  CONVERSATION_THREAD_NOT_USABLE: 409,
  THREAD_PARTICIPANT_MISMATCH: 409,
  MESSAGE_NOT_DRAFT: 409,
  MESSAGE_VERSION_CONFLICT: 409,
  SEND_CONFIRMATION_REQUIRED: 409,
  SEND_CONFIRMATION_EXPIRED: 409,
  SEND_CONFIRMATION_MISMATCH: 409,
  ATTACHMENT_NOT_READY: 409,
  MESSAGE_ALREADY_QUEUED: 409,
  MESSAGE_DELIVERY_STATE_CONFLICT: 409,
  MESSAGE_DELIVERY_UNKNOWN: 409,
  MESSAGE_CANNOT_BE_WITHDRAWN: 409,
  PROVIDER_CALLBACK_INVALID: 400,
  PROVIDER_REFERENCE_UNKNOWN: 404,

  // Resource state
  RESOURCE_NOT_FOUND: 404,
  RESOURCE_CONFLICT: 409,
  VERSION_CONFLICT: 412,
  INVALID_STATE_TRANSITION: 409,
  IMMUTABLE_RESOURCE: 409,
  RESOURCE_WITHDRAWN: 410,
  RESOURCE_RESTRICTED: 403,

  // Workflow
  CONFIRMATION_REQUIRED: 409,
  HUMAN_REVIEW_REQUIRED: 409,
  APPROVAL_REQUIRED: 409,
  MODERATION_REVIEW_REQUIRED: 409,
  SAFETY_REVIEW_REQUIRED: 409,
  DATASET_LOCK_NOT_READY: 409,
  EXPORT_REQUIRES_APPROVAL: 409,

  // Request
  VALIDATION_ERROR: 400,
  UNSUPPORTED_FILTER: 400,
  UNSUPPORTED_CAPABILITY: 400,
  IDEMPOTENCY_CONFLICT: 409,
  PAYLOAD_TOO_LARGE: 413,
  RATE_LIMITED: 429,

  // Dependency
  DEPENDENCY_UNAVAILABLE: 503,
  PROVIDER_TIMEOUT: 504,
  PROVIDER_REJECTED: 502,
  DELIVERY_UNCONFIRMED: 502,
  BLOCK_PROPAGATION_PENDING: 409,
  DATA_QUALITY_FAILURE: 409,
  LINEAGE_INCOMPLETE: 409,
  DEIDENTIFICATION_REQUIRED: 409,
  PARTIAL_RESULT: 206,

  // Internal
  AUDIT_UNAVAILABLE: 503,
  INTERNAL_ERROR: 500,
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;

export function httpStatusFor(code: ErrorCode): number {
  return ERROR_CODES[code];
}

/** Codes that are safe to retry without a state change (Doc 15 error format `retryable`). */
export const RETRYABLE_CODES: ReadonlySet<ErrorCode> = new Set<ErrorCode>([
  'RATE_LIMITED',
  'DEPENDENCY_UNAVAILABLE',
  'PROVIDER_TIMEOUT',
  'AUDIT_UNAVAILABLE',
  'INTERNAL_ERROR',
]);
